### ISSUE TITLE
Add support for RTCRtpSenders and RTCRtpReceivers

### ISSUE THREAD

**Issue by markandrus** [node-webrtc/node-webrtc#394]
We should support RTCRtpSenders and RTCRtpReceivers. WebRTC M60 has support for these, so we just need to surface them. Eventually we'll want to add RTCRtpTransceivers, but we need to update libwebrtc first. This ticket doesn't consider local MediaStreamTracks—initially we'll just unblock "relaying" remote MediaStreamTracks. For example, given some RTCPeerConnection `pc` and remote RTCSessionDescription `offer`, we should be able to do the following:

```js
(async () => {
  await pc.setRemoteDescription(offer)
  const receivers = pc.getReceivers()
  receivers.forEach(receiver => pc.addTrack(receiver.track))
  const answer = await pc.createAnswer()
  await pc.setLocalDescription()
})()
```

- [x] Add support for RTCRtpReceivers — #393
  - [x] `track` — #393
  - [x] `transport`
  - [ ] `rtcpTransport`
  - [x] `getParameters`
  - [x] `getContributingSources`
  - [x] `getSynchronizationSources`
  - [ ] `getStats`
  - [ ] `getCapabilities`
- [x] Add support for remote MediaStreamTracks — #393
- [x] Add support for RTCTrackEvent — #393
  - [x] `track`
  - [x] `receiver`
  - [x] `streams` — #398
  - [x] `transceiver` — #446 
  - [ ] RTCTrackEvent
- [x] Add support for `getReceivers` — #393
- [x] Add tests for receiving remote MediaStreamTracks — #393
- [x] Add support for RTCRtpSenders — #398 
  - [x] `track`
  - [x] `transport`
  - [ ] `rtcpTransport`
  - [x] `replaceTrack` — #398
  - [x] `getParameters` — #398
  - [x] `setParameters` — #398
  - [ ] `getStats` — #398
- [x] Add support for `getSenders` — #398
- [x] Add support for `addTrack` — #398
  - [x] `addTrack(track, stream)` — #398
  - [x] `addTrack(track)` — #446
  - [ ] `addTrack(track, stream1, stream2)`
- [x] Add support for `removeTrack` — #398
- [x] Add tests for sending remote MediaStreamTracks — #398

**Comment by zsmweb** [comment]
I wish you could support getSelectedCandidatePair api. Great thanks!

**Comment by markandrus** [comment]
@zsmweb Looks like `getSelectedCandidatePair` is a member of RTCIceTransport added in M73. I've opened https://github.com/node-webrtc/node-webrtc/issues/493 to track.

**Comment by t-mullen** [comment]
Any plans for `addTransceiver()` and `getTransceivers()`? They are necessary for dynamic tracks and non-initiator -> initiator streaming without using the old constraints API.

**Comment by markandrus** [comment]
Hi @t-mullen, there is some support already. See the checklist here: https://github.com/node-webrtc/node-webrtc/issues/395

**Comment by markandrus** [comment]
RTCRtpSenders and RTCRtpReceivers have largely been available in the library for a while now. There are a few remaining things, but I think those could be better tracked on dedicated issues as requested by the community. Closing.
