### ISSUE TITLE
Add support for RTCRtpTransceivers

### ISSUE THREAD

**Issue by markandrus** [node-webrtc/node-webrtc#395]
- [x] Update libwebrtc to a version that supports RTCRtpTransceivers
- [ ] Add support for RTCRtpTransceiver
  - [x] Initial implementation — #446 
  - [x] `mid`
  - [x] `sender`
  - [x] `receiver`
  - [x] `stopped`
  - [x] `direction`
  - [x] `currentDirection`
  - [x] `stop`
  - [x] `setCodecPreferences` — #580
  - [ ] `getStats`
- [x] Add support for `addTransceiver(kind)` and `addTransceiver(track)`
  - [x] `addTransceiver(kind)` — #446 
  - [x] `addTransceiver(track)` — #446
- [ ] Add support for RTCRtpTransceiverInit/`addTransceiver(kindOrTrack, init)`
  - [x] `direction` — #446
  - [x] `streams`
  - [ ] `sendEncodings`
- [x] Add support for `getTransceivers` — #446 
- [x] Add test for adding RTCRtpTransceivers
- [x] Try passing some of the web-platform-tests that require RTCRtpTransceivers
  - [x] Some new ones are passing — #446 
  - [x] Some web-platform-tests are out-of-date WRT the spec and need PRs
- [x] Add support for `sdpSemantics` — #446

**Comment by markandrus** [comment]
RTCRtpTransceiver has largely been available in the library for a while now. There are a few remaining things, but I think those could be better tracked on dedicated issues as requested by the community. Closing.
