### ISSUE TITLE
Add support for MediaStream

### ISSUE THREAD

**Issue by markandrus** [node-webrtc/node-webrtc#396]
This issue only tracks the addition of MediaStream support insofar as MediaStream is a "smart collection" of MediaStreamTracks. That is, this issue is complete once we can do the following, given some existing MediaStreamTrack, `track`,

```js
const stream = new MediaStream()
stream.addTrack(track)
```

plus any other checklist items below. `getUserMedia` is not in scope here, nor is creation of local MediaStreamTracks.

- [x] Add support for MediaStream — #398 
  - [x] constructor
    - [x] `new MediaStream()` — #398 
    - [x] `new MediaStream(stream)` — #398
    - [x] `new MediaStream(tracks)` — #398
  - [x] `id` — #398
  - [x] `getTracks` — #398
  - [x] `getAudioTracks` — #398
  - [x] `getVideoTracks` — #398
  - [x] `getTrackById` — #398
  - [x] `addTrack` — #398
  - [x] `removeTrack` — #398
  - [x] `clone`
  - [x] `active` — #398
  - [ ] `onaddtrack`
  - [ ] `onremovetrack`
- [x] Add support for `streams` in RTCTrackEvent — #398
- [x] Add support for `streams` in PeerConnection's `addTrack` — #398

**Comment by avaer** [comment]
@markandrus is this list still accurate? I'd like to jump in and help but it's hard to get a lay of the land.

Specifically I'm just trying to get a mic MediaStream working and looking to what we need to finish for that.

There's also https://github.com/js-platform/node-webrtc/issues/220#issuecomment-383390412.

**Comment by markandrus** [comment]
Hi, @modulesio! Yes, this last is accurate and the checked-off features have been released.

> Specifically I'm just trying to get a mic MediaStream working and looking to what we need to finish for that.

You want to acquire a MediaStream using node-webrtc that contains an audio MediaStreamTrack capturing from a microphone on the host machine? If so, we should plan out work to support `getUserMedia`. Some thoughts:

1. In order to access the microphone, we'll need to be able to create a PeerConnectionFactory that uses the default audio device for the platform node-webrtc is running on. See [here](https://github.com/js-platform/node-webrtc/blob/v0.1.6/src/peerconnectionfactory.cc#L64).
2. By default, we need to continue preferring the fake audio device.
3. Probably we should either:

    1. Parameterize the RTCPeerConnection constructor (and an eventual `getUserMedia` method) to accept the PeerConnectionFactory, or
    2. Let PeerConnectionFactory return a new RTCPeerConnection constructor and `getUserMedia` method.

    Personally, Option 2 feels more correct; although, I'm not sure if it will be difficult to implement.

4. (I think) we need to protect calls to `addTrack`/`addStream` on RTCPeerConnection such that only MediaStreamTracks constructed from the same PeerConnectionFactory can be added, although I'm not quite sure.

I can create a tracking issue.

**Comment by avaer** [comment]
Hm, I'm of the (uninformed) opinion that `getUserMedia` is perhaps outside the scope of WebRTC proper.

That's because you can `getUserMedia` without having anything to do with RTC -- I actually have `getUserMedia` already in my browser via [Labsound](https://github.com/LabSound/LabSound).

But naturally that needs to plug into RTC. Is that what the [FakeAudioDevice::Capturer](https://github.com/js-platform/node-webrtc/blob/v0.1.6/src/webrtc/fake_audio_device.h#L50) is about?

I just figure by using `node-webrtc` one is probably trying to plug in to some media streams of their own making, not trying to create a mic listener. So I'm trying to think of what the integration point is/could be for that case.

Thanks for the code pointers!

**Comment by markandrus** [comment]
@modulesio 

> Hm, I'm of the (uninformed) opinion that `getUserMedia` is perhaps outside the scope of WebRTC proper.
>
> That's because you can `getUserMedia` without having anything to do with RTC -- I actually have `getUserMedia` already in my browser via [Labsound](https://github.com/LabSound/LabSound).

Yes, `getUserMedia` is defined in [`mediacapture-main`](https://w3c.github.io/mediacapture-main/#mediadevices-interface-extensions) rather than, e.g., [`webrtc-pc`](https://w3c.github.io/webrtc-pc/), and can be used independently of WebRTC. You could make the argument that node-webrtc doesn't need to provide a `getUserMedia` implementation, but there are many use cases (e.g., using node-webrtc to test a browser library) where being able to run the same or similar code in a Node test process versus the browser would be convenient. Providing `getUserMedia` would let us skip the work of defining a new, non-standard API, too—at least for local capture.

> But naturally that needs to plug into RTC. Is that what the [FakeAudioDevice::Capturer](https://github.com/js-platform/node-webrtc/blob/v0.1.6/src/webrtc/fake_audio_device.h#L50) is about?

Yes, a capturer will be necessary to construct local MediaStreamTracks. We may want to bind such APIs directly in node-webrtc. I've experimented in the past with a capturer that lets you pump frames or audio directly from Node. My feeling is this is probably not the most performant approach (maybe others have suggestions?), but it worked for a demo.

> I just figure by using `node-webrtc` one is probably trying to plug in to some media streams of their own making, not trying to create a mic listener. So I'm trying to think of what the integration point is/could be for that case.

Sorry, can you clarify what use case/feature you would like? :-) I thought you were interested in capturing the local microphone from Node. Are you instead interested in pumping your own audio through, e.g. via a custom capturer? We could also track some work for that.

> Thanks for the code pointers!

NP, also LabSound looks cool :-D

**Comment by avaer** [comment]
> I thought you were interested in capturing the local microphone from Node

Correct -- but that part is done! We have a `WebAudio`, microphone `MediaStream`, and `getUserMedia` running on `node` [already](https://github.com/webmixedreality/exokit/blob/master/deps/exokit-bindings/webaudiocontext/src/MicrophoneMediaStream.cpp#L33). But there is no RTC.

So the use case is having the full RTC api in Javascript, but using our own stream for pumping I/O. In my mind this looks like e.g.

```
// set up RTC...
inputTrack = new InputMediaStreamTrack({
  read() {
     return samples; // 10ms or such
  }
});
pc.addTrack(inputTrack);
pc.ontrack = track => {
  outputTrack = new OutputMediaStreamTrack({
    track,
    read(samples) {
       // got some samples, maybe buffer for hardware or pipe to disk
    }
  });
  // ...
  outputTrack.close();
};
```

I don't know if this is a desirable binding, but it seems very general. With the above, the I/O methods could of course be implemented native, or turned into node streams as the use case requires.

Do you have the demo code with the node streams?

**Comment by paco3346** [comment]
@markandrus I would be interested in doing local microphone capture with just node. (I have a remote endpoint running on a RPi that I want to stream to a browser).

I've been playing around with https://github.com/thedracle/node-webrtc/tree/mediastream-rebase-squash ever since Dracle forked webrtc but haven't yet figured out what I'm missing. His work adds `getUserMedia` but I can't figure out how to add tracks.

If I'm reading this issue correctly it looks like you're adding `addTrack` support but not `getUserMedia`, right?

**Comment by markandrus** [comment]
@modulesio the binding/API you describe is roughly what WebRTC's Audio/Video Source/Sink APIs provide. I implemented RTCVideoSink and RTCVideoSource in [v0.3.5](https://github.com/node-webrtc/node-webrtc/releases/tag/v0.3.5), and I'm working on RTCAudioSink and RTCAudioSource [here](https://github.com/node-webrtc/node-webrtc/pull/479). With it, I think you'd be able to hook up your example, although I'm not sure how performant it would be. Also, I don't think the APIs WebRTC is exposing at this level have enough information to synchronize audio/video. For hacks/toy examples, this may be OK, but something to consider&hellip;

@paco3346 I mention this in [the other thread](https://github.com/node-webrtc/node-webrtc/issues/266#issuecomment-458782987), but I think local hardware access (microphone, webcam) is a little higher level and a separate feature in its own right. We can support this, but it deserves its own tracking issue, e.g. "Microphone Capture." (We have lots of issues related to audio, video, MediaStream, etc., and often times people are asking for different things.)

**Comment by t-mullen** [comment]
If anyone tries dumping this audio to a disk, here's the commands to do it (getting the format options right took some time).

```javascript
const track = stream.getAudioTracks()[0]
const sink = new wrtc.nonstandard.RTCAudioSink(track)
const writeStream = fs.createWriteStream('./output.pcm')
sink.ondata = (event) => {
  writeStream.write(Buffer.from(event.samples))
}
```
Then convert to a more playable format like WAV with FFMPEG:
```
ffmpeg -f s16le -ar 48k -ac 1 -i output.pcm -acodec copy -f wav -ar 48k -ac 1 output.wav -y
```

It's import your file has the `.pcm` extension, or FFMPEG and VLC will just play noise.

**Comment by markandrus** [comment]
MediaStream has largely been available in the library for a while now. There are a few remaining event handlers, but I think those could be better tracked on dedicated issues as requested by the community. Closing.
