### ISSUE TITLE
Move from NAN to N-API

### ISSUE THREAD

**Issue by markandrus** [node-webrtc/node-webrtc#504]
By adopting N-API, we should be able to reduce the size of our build matrix from

> NODE_VERSIONS x DEBUG/RELEASE x ARCH/PLATFORM

to a much more manageable

> DEBUG/RELEASE x ARCH/PLATFORM

This will be a big effort, and I expect we'll find things that N-API is missing. For that reason, I think we should attempt a gradual transition.

- [x] Add N-API `node_webrtc::Converter` instances for enums and dictionaries (no interfaces).
  - [x] Basic v8 types — #507
  - [x] Enums — #507
  - [x] Dictionaries — #507
  - [x] Interfaces
- [x] Start using N-API `node_webrtc::Converter` instances for enums and dictionaries. **Note:** This may be blocked on adopting ObjectWrap (see below).
  - [x] `getUserMedia` — #507
  - [x] I420Helpers
  - [x] Interface methods
- [x] Replace `uv_mutex`, `uv_lock`, etc., with `std::mutex`, etc., in non-libuv-specific code. — #507
- [x] Implement `node_webrtc::EventLoop` in terms of N-API.
- [x] Refactor `node_webrtc::Promise` and related functions to use N-API.
- [x] Tackle ObjectWrap&hellip; (this seems trickiest, as even with NAN it's been complicated).
  - [x] RTCVideoSource (ObjectWrap) — #507
  - [x] RTCAudioSource (ObjectWrap) — #507
  - [x] MediaStream (ObjectWrap) — #507
  - [x] `src/interfaces/legacy_rtc_stats_report.{h,cc}` (ObjectWrap) — #507
  - [x] `src/interfaces/rtc_stats_response.{h,cc}` (ObjectWrap) — #507
  - [x] RTCRtpSender (AsyncObjectWrap) — #507
  - [x] RTCRtpReceiver (AsyncObjectWrap)
  - [x] RTCRtpTransceiver (AsyncObjectWrap)
  - [x] MediaStreamTrack (AsyncObjectWrapWithLoop)
  - [x] RTCAudioSink (AsyncObjectWrapWithLoop)
  - [x] RTCVideoSink (AsyncObjectWrapWithLoop)
  - [x] RTCDataChannel (AsyncObjectWrapWithLoop)
  - [x] RTCDtlsTransport (AsyncObjectWrapWithLoop)
  - [x] RTCPeerConnection (AsyncObjectWrapWithLoop)
- [x] Identify, remove, and/or replace any remaining usages of nan.
- [x] Identify, remove, and/or replace any remaining usages of v8.

Likely other things will need to be added to this list over time.

**Comment by markandrus** [comment]
This is done and will land in v0.4—w00t
